// Code generated by MockGen. DO NOT EDIT.
// Source: pthd-bot/pkg/interfaces (interfaces: ITeamKillLogDAO)

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "pthd-bot/pkg/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockITeamKillLogDAO is a mock of ITeamKillLogDAO interface.
type MockITeamKillLogDAO struct {
	ctrl     *gomock.Controller
	recorder *MockITeamKillLogDAOMockRecorder
}

// MockITeamKillLogDAOMockRecorder is the mock recorder for MockITeamKillLogDAO.
type MockITeamKillLogDAOMockRecorder struct {
	mock *MockITeamKillLogDAO
}

// NewMockITeamKillLogDAO creates a new mock instance.
func NewMockITeamKillLogDAO(ctrl *gomock.Controller) *MockITeamKillLogDAO {
	mock := &MockITeamKillLogDAO{ctrl: ctrl}
	mock.recorder = &MockITeamKillLogDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITeamKillLogDAO) EXPECT() *MockITeamKillLogDAOMockRecorder {
	return m.recorder
}

// GetTopKillers mocks base method.
func (m *MockITeamKillLogDAO) GetTopKillers(arg0 string) ([]*entities.TopKillerLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopKillers", arg0)
	ret0, _ := ret[0].([]*entities.TopKillerLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopKillers indicates an expected call of GetTopKillers.
func (mr *MockITeamKillLogDAOMockRecorder) GetTopKillers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopKillers", reflect.TypeOf((*MockITeamKillLogDAO)(nil).GetTopKillers), arg0)
}

// GetTopVictims mocks base method.
func (m *MockITeamKillLogDAO) GetTopVictims(arg0 string) ([]*entities.TopVictimLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopVictims", arg0)
	ret0, _ := ret[0].([]*entities.TopVictimLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopVictims indicates an expected call of GetTopVictims.
func (mr *MockITeamKillLogDAOMockRecorder) GetTopVictims(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopVictims", reflect.TypeOf((*MockITeamKillLogDAO)(nil).GetTopVictims), arg0)
}

// Save mocks base method.
func (m *MockITeamKillLogDAO) Save(arg0 *entities.TeamKill) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockITeamKillLogDAOMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockITeamKillLogDAO)(nil).Save), arg0)
}
