services:
  teamkillbot:
    build: .
    environment:
      tkbot_db_path: /host-mnt/teamkillbot.sqlite
      tkbot_tg_token: $tkbot_tg_token
      tkbot_chat_id: $tkbot_chat_id
    volumes:
      - ./volumes/teamkillbot/:/host-mnt